# -*- coding: utf-8 -*-
"""Traffic_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bn5ZYORDL5-6gqELWf7zTcCsziqePC1
"""

import pandas as pd
df = pd.read_csv("traffic_accidents.csv")
df.head()

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (10,5)
sns.set_style("whitegrid")

print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())
df.info()

df.describe()

cat_cols = df.select_dtypes(include='object').columns
df[cat_cols] = df[cat_cols].fillna("UNKNOWN")
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

df['crash_date'] = pd.to_datetime(df['crash_date'])
df['year'] = df['crash_date'].dt.year
df['month'] = df['crash_date'].dt.month
df['day'] = df['crash_date'].dt.day

sns.countplot(x='crash_hour', data=df)
plt.title("Accidents by Hour of Day")
plt.show()

sns.countplot(x='crash_day_of_week', data=df,color="brown")
plt.title("Accidents by Day of Week")
plt.show()

sns.countplot(x='crash_month', data=df,color="lightgreen")
plt.title("Accidents by Month")
plt.show()

sns.countplot(y='weather_condition', data=df,
              order=df['weather_condition'].value_counts().index,color="pink")
plt.title("Accidents by Weather Condition")
plt.show()

sns.countplot(y='lighting_condition', data=df,
              order=df['lighting_condition'].value_counts().index,color="yellow")
plt.title("Accidents by Lighting Condition")
plt.show()

sns.countplot(y='roadway_surface_cond', data=df,
              order=df['roadway_surface_cond'].value_counts().index,color="blue")
plt.title("Accidents by Road Surface Condition")
plt.show()

sns.countplot(y='road_defect', data=df,
              order=df['road_defect'].value_counts().index,color="teal")
plt.title("Accidents due to Road Defects")
plt.show()

sns.countplot(y='trafficway_type', data=df,
              order=df['trafficway_type'].value_counts().index,color="orange")
plt.title("Accidents by Trafficway Type")
plt.show()

hourly_accidents = df.groupby('crash_hour').size()

plt.figure()
hourly_accidents.plot(kind='line', marker='o',color="purple")
plt.xlabel('Hour of Day')
plt.ylabel('Number of Accidents')
plt.title('Hourly Trend of Traffic Accidents')
plt.show()

monthly_accidents = df.groupby('crash_month').size()

plt.figure()
monthly_accidents.plot(kind='line', marker='o',color="red")
plt.xlabel('Month')
plt.ylabel('Number of Accidents')
plt.title('Monthly Trend of Traffic Accidents')
plt.show()

sns.countplot(y='first_crash_type', data=df,
              order=df['first_crash_type'].value_counts().index,color="silver")
plt.title("First Crash Type Distribution")
plt.show()

crash_counts = df['crash_type'].value_counts()
crash_percent = crash_counts / crash_counts.sum() * 100

plt.figure()
crash_counts.plot(kind='barh')
plt.xlabel('Number of Accidents')
plt.title('Crash Type Distribution with Proportions')

for i, v in enumerate(crash_counts):
    plt.text(v, i, f"{crash_percent[i]:.1f}%")

plt.show()

sns.countplot(x='intersection_related_i', data=df,color="purple")
plt.title("Intersection Related Accidents")
plt.show()

sns.countplot(y='damage', data=df,
              order=df['damage'].value_counts().index,color="green")
plt.title("Damage Severity Distribution")
plt.show()

severity_light = pd.crosstab(df['lighting_condition'], df['most_severe_injury'])

severity_light.plot(kind='bar', stacked=True)
plt.title('Accident Severity by Lighting Condition')
plt.xlabel('Lighting Condition')
plt.ylabel('Count')
plt.show()

df['most_severe_injury'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribution of Accident Severity')
plt.ylabel('')
plt.show()

vehicle_counts = df['num_units'].value_counts().sort_index()

plt.figure()
plt.pie(
    vehicle_counts,
    labels=vehicle_counts.index,
    autopct='%1.1f%%',
    startangle=90
)
plt.title('Proportion of Accidents by Number of Vehicles Involved')
plt.show()

pivot = df.pivot_table(
    index='crash_day_of_week',
    columns='crash_hour',
    values='injuries_total',
    aggfunc='count'
)

sns.heatmap(pivot, cmap='Reds')
plt.title("Crash Density Heatmap (Day vs Hour)")
plt.show()

features = [
    'crash_hour',
    'crash_day_of_week',
    'crash_month',
    'weather_condition',
    'lighting_condition',
    'roadway_surface_cond',
    'trafficway_type',
    'num_units'
]

ml_df = df[features + ['most_severe_injury']]

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in ml_df.select_dtypes(include='object'):
    ml_df[col] = le.fit_transform(ml_df[col])

from sklearn.model_selection import train_test_split

X = ml_df.drop('most_severe_injury', axis=1)
y = ml_df['most_severe_injury']
X = pd.get_dummies(X)
X_columns = X.columns
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

sample_input = pd.DataFrame({
    'crash_hour': [22],
    'crash_day_of_week': [5],
    'crash_month': [8],
    'weather_condition': [1],
    'lighting_condition': [2],
    'roadway_surface_cond': [0],
    'trafficway_type': [3],
    'num_units': [2]
})

prediction = model.predict(sample_input)
print("Predicted Injury Severity Class:", prediction[0])

!pip install gradio

import gradio as gr
import pandas as pd

def predict_severity(
    crash_hour,
    crash_day_of_week,
    crash_month,
    weather_condition,
    lighting_condition,
    roadway_surface_cond,
    trafficway_type,
    num_units
):
    try:
        # Create input dataframe
        input_df = pd.DataFrame([{
            'crash_hour': crash_hour,
            'crash_day_of_week': crash_day_of_week,
            'crash_month': crash_month,
            'weather_condition': weather_condition,
            'lighting_condition': lighting_condition,
            'roadway_surface_cond': roadway_surface_cond,
            'trafficway_type': trafficway_type,
            'num_units': num_units
        }])

        # One-hot encode
        input_encoded = pd.get_dummies(input_df)

        # Align with training columns
        input_encoded = input_encoded.reindex(
            columns=X_columns,
            fill_value=0
        )

        # Prediction
        prediction = model.predict(input_encoded)[0]

        return f"✅ Predicted Accident Severity: {prediction}"

    except Exception as e:
        return f"❌ Error occurred: {str(e)}"

import gradio as gr

interface = gr.Interface(
    fn=predict_severity,
    inputs=[
        gr.Slider(0, 23, step=1, label="Crash Hour"),
        gr.Slider(1, 7, step=1, label="Day of Week (1=Mon, 7=Sun)"),
        gr.Slider(1, 12, step=1, label="Month"),
        gr.Dropdown(df['weather_condition'].unique().tolist(), label="Weather Condition"),
        gr.Dropdown(df['lighting_condition'].unique().tolist(), label="Lighting Condition"),
        gr.Dropdown(df['roadway_surface_cond'].unique().tolist(), label="Road Surface Condition"),
        gr.Dropdown(df['trafficway_type'].unique().tolist(), label="Trafficway Type"),
        gr.Slider(1, 10, step=1, label="Number of Vehicles Involved")
    ],
    outputs=gr.Textbox(label="Prediction Result"),
    title="🚦 Traffic Accident Severity Predictor",
    description="Predict accident severity based on crash conditions"
)

interface.launch(share=True)







